# Generated by Django 2.2.4 on 2021-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facker_appe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
